### ISSUE TITLE
Use native Object.assign instead of xtend

### ISSUE THREAD

**Issue by jimmywarting** [goto-bus-stop/minify-stream#3]
[xtend](https://github.com/Raynos/xtend) can easily be replaced with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

This reduce the dependencies and possible also avoid duplicated versions where some package don't use the same version range for the xtend package

```js
// immutable
Object.assign({}, a, b)

// mutable
Object.assign(a, b)
```

**Comment by goto-bus-stop** [comment]
thanks for the suggestion—i want minify-stream to be as backwards compatible as it can reasonably be, so i won't do this for now. I might upgrade the default terser version in a future major release though, which would raise the support floor enough to use Object.assign at that point.
